_welcome:
    pattern:  /
    defaults: { _controller: LesBonnesChosesBundle:Main:index }

_product:
    pattern: /products/{id}/{slug}
    defaults: { _controller: LesBonnesChosesBundle:Main:product }

